function createfigure(cdata1)
%CREATEFIGURE(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 28-Nov-2015 11:10:09

% Create figure
figure1 = figure;
colormap('gray');

% Create axes
axes1 = axes('Visible','off','Parent',figure1,'Layer','top','TickDir','out',...
    'YDir','reverse',...
    'Position',[0.404344383445946 0.28125 0.189189189189189 0.21875],...
    'DataAspectRatio',[1 1 1]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.5 28.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.5 28.5]);
box(axes1,'on');
hold(axes1,'on');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

